# Generated by Django 3.0.6 on 2020-08-07 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract',
            name='open_qty',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='qty',
            field=models.SmallIntegerField(),
        ),
    ]
