# Generated by Django 3.0.6 on 2020-08-08 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('log', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='reference',
            new_name='ref',
        ),
    ]
